Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]

blogs/urls.py
"""Defines URL patterns for blogs"""
from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
	# Home page 
	path('', views.blogs, name='blogs'),
	# Page for adding new blog
	path('new_blog/', views.new_blog, name='new_blog'),
	# Page for editing URLs
	path('edit_blog/<int:blog_id>', views.edit_blog, name='edit_blog'),
]

users/urls.py
"""Defines URL patterns for users."""
from django.urls import path, include
from . import views


app_name = 'users'
urlpatterns = [
	# Include default auth urls.
	path('', include('django.contrib.auth.urls')),
	# Registration page.
	path('register/', views.register, name='register'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

class BlogPost(models.Model):
	"""A blog model."""
	title = models.CharField(max_length=200)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User, on_delete=models.CASCADE)

	class Meta:
		verbose_name_plural = 'entries'

	def __str__(self):
		"""Retrun a title and text represention of the model."""
		return f"{self.title}: {self.text[:50]}..."

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms
from .models import BlogPost
 
class BlogForm(forms.ModelForm):
	class Meta:
		model = BlogPost
		fields = ['title', 'text']
		labels = {'text': ''}
		widgets = {'text': forms.Textarea(attrs={'cols': 80})}

blogs/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import BlogPost

from .forms import BlogForm

def check_blog_owner(blog, request):
   """Make sure the topic blongs to the current topic."""
   if blog.owner != request.user:
        raise Http404

def blogs(request):
    """Show all blogs."""
    blogs = BlogPost.objects.filter(owner=request.user.id).order_by('date_added')
    context = {'blogs': blogs}
    return render(request, 'blogs/blogs.html', context)

@login_required
def new_blog(request):
	"""Creating new Blog"""

	if request.method != 'POST':
		# No data submitted; create a blank form.
		form = BlogForm()
	else:
		# POST data submitted; process data.
		form = BlogForm(data=request.POST)
		if form.is_valid():
			new_blog = form.save(commit=False)
			new_blog.save()
			return redirect('blogs:blogs')

	# Display a blank or invalid form.
	context = {'form': form}
	return render(request, 'blogs/new_blog.html', context)

@login_required
def edit_blog(request, blog_id):
	"""Edit an existing Blog."""
	blog = BlogPost.objects.get(id=blog_id)
	check_blog_owner(blog, request)

	if request.method != 'POST':
		# Initial request; pre-fill form with the current entry.
		form = BlogForm(instance=blog)
	else:
		# POST data submitted; process data.
		form = BlogForm(instance=blog, data=request.POST)
		if form.is_valid():
			form.save()
			return redirect('blogs:blogs')
	
	context = {'blog': blog, 'form': form}
	return render(request, 'blogs/edit_blog.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
	"""Register a new user."""

	if request.method != 'POST':
		# Display blank registration form.
		form = UserCreationForm()
	else:
		# Display blank registration form.
		form = UserCreationForm(data=request.POST)

		if form.is_valid():
			new_user = form.save()
			# Log the user in and then redirect to home page.
			login(request, new_user)
			return redirect('blogs:blogs')


	# Display a blank or invalid form.
	context = {'form': form}
	return render(request, 'registration/register.html', context)

blogs/templates/blogs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<title>Blog</title>

	{% bootstrap_css %}
	{% bootstrap_javascript jquery='full' %}

</head>

<body>
	<nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

		<a class="navbar-brand" href="{% url 'blogs:blogs'%}">Blog</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
		
		
		<span class="navbar-toggler-icon"></span></button>
		<div class="collapse navbar-collapse" id="navbarCollapse">
			<ul class="navbar-nav ml-auto">
			  {% if user.is_authenticated %}
			 	<li class="nav-item">
			 		<span class="navbar-text">Hello, {{ user.username }}.</span>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
				</li>
			  {% else %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'users:register' %}">Register</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
			  {% endif %}
			</ul>		
		</div>
	</nav>

	<main role="main" class="container">
		<div class="pb-2 mb-2 border-bottom">
			{% block page_header %}{% endblock page_header %}
		</div>
		<div>
			{% block content %}{% endblock content %}
		</div>
	</main>
		
</body>

</html>

blogs/templates/blogs/blogs.html
{% extends 'blogs/base.html' %}

{% block page_header %}
	<h3>Blogs:</h3>
{% endblock page_header %}

{% block content %}


<ul>
	{% for blog in blogs %}
		<div class="card mb-3">
			<h4 class="card-header">
				{{ blog.date_added|date:'M d, Y H:i' }}
				<small><a href="{% url 'blogs:edit_blog' blog.id %}">edit blog</a></small>
			</h4>
			<div>
				{{ blog.text|linebreaks }}
			</div>
		</div>
	{% empty %}
		<p>There are no entries for this topic yet.</p>
	{% endfor %}	
			

<a href="{% url 'blogs:new_blog' %}">Add a new blog</a>

{% endblock content %}

blogs/templates/blogs/edit_blog.html
{% extends 'blogs/base.html' %}

{% load bootstrap4 %}

{% block page_header %}
    <h2>Edit blog:.</h2>
{% endblock page_header %}



{% block content %}

    <form method="post" action="{% url 'blogs:edit_blog' blog.id %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">save changes</button>
        {% endbuttons %}

        <input type="hidden" name="next" value="{% url 'blogs:blogs' %}">
    </form>

{% endblock content %}

blogs/templates/blogs/new_blog.html
{% extends 'blogs/base.html' %}


{% load bootstrap4 %}

{% block page_header %}
	<h2>Add a new blog:.</h2>
{% endblock page_header %}


{% block content %}

	<form method="post" action="{% url 'blogs:new_blog' %}" class="form">
		{% csrf_token %}
		{% bootstrap_form form %}
		{% buttons %}
			<button name="submit" class="btn btn-primary">Add blog</button>
		{% endbuttons %}

		<input type="hidden" name="next" value="{% url 'blogs:blogs' %}">
	</form>

{% endblock content %}